# Generated by Django 5.1.6 on 2025-03-21 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvizFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='125 Characters allowed', max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Aviz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='64 Characters allowed', max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_area', models.PositiveSmallIntegerField()),
                ('rooms', models.PositiveSmallIntegerField(default=1)),
                ('floor', models.PositiveSmallIntegerField()),
                ('year_of_construction', models.DateField()),
                ('price_per_meter', models.PositiveSmallIntegerField()),
                ('price', models.PositiveSmallIntegerField()),
                ('is_hot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilities', models.ManyToManyField(to='ad_app.avizfacilities')),
            ],
            options={
                'verbose_name': 'Aviz',
                'verbose_name_plural': 'Avizs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvizPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(height_field='poster_height', upload_to='posters', width_field='poster_width')),
                ('poster_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('poster_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, help_text='in kilobytes')),
                ('aviz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='ad_app.aviz')),
            ],
        ),
    ]
