# Generated by Django 5.1.6 on 2025-03-24 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0002_avizfacilities_aviz_avizposter'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avizs', to='ad_app.subcategory'),
        ),
        migrations.AlterField(
            model_name='avizfacilities',
            name='title',
            field=models.CharField(help_text='64 Characters allowed', max_length=64),
        ),
    ]
