# Generated by Django 5.1.6 on 2025-03-24 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0003_aviz_category_alter_avizfacilities_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviz',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avizs', to='ad_app.subcategory'),
        ),
    ]
