# Generated by Django 5.1.6 on 2025-04-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0004_alter_aviz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviz',
            name='year_of_construction',
            field=models.PositiveIntegerField(),
        ),
    ]
