# Generated by Django 5.1.6 on 2025-05-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0005_alter_aviz_year_of_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviz',
            name='call_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aviz',
            name='chat_available',
            field=models.BooleanField(default=True),
        ),
    ]
