# Generated by Django 5.1.6 on 2025-05-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0006_aviz_call_available_aviz_chat_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviz',
            name='is_location_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aviz',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aviz',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
