# Generated by Django 5.1.6 on 2025-05-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0007_aviz_is_location_allowed_aviz_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviz',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='aviz',
            name='price_per_meter',
            field=models.PositiveIntegerField(),
        ),
    ]
