# Generated by Django 5.1.6 on 2025-05-21 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0008_alter_aviz_price_alter_aviz_price_per_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviz',
            name='description',
            field=models.TextField(blank=True, help_text='1000 Characters allowed', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='aviz',
            name='floor',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100, message='Number of floor must be a positive integer less than 100')]),
        ),
        migrations.AlterField(
            model_name='aviz',
            name='rooms',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100, message='Number of rooms must be a positive integer less than 100')]),
        ),
        migrations.AlterField(
            model_name='aviz',
            name='total_area',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000000, message='Total area must be a positive integer less than 10,000,000.')]),
        ),
        migrations.AlterField(
            model_name='aviz',
            name='year_of_construction',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1405, message='year of construction must be less than 1406'), django.core.validators.MinValueValidator(1300, message='year of construction must be greater than 1300')]),
        ),
    ]
